### PR TITLE
Se implemento la pantalla de login a la app sin funcionalidades

### PR DESCRIPTION
**Pull request by Matarratas777**
Co-authored-by: GaddPat0609
Co-authored-by: EliasCode79

# Description

the login screen was implemented in the application without functionalities

- By reusing various components of the registration screen, it was possible to create the following screen, which would be the login screen, which will offer the option to log in if you already have an account created.
image

### CODE REVIEW

**Review by McFly1208 — APPROVED** [review]
LGTM

**Review by RobertoCarMed — APPROVED** [review]

**Review by IvanGodinez21 — APPROVED** [review]
GREAT JOB! 🍆🐒

**Comment by HenrikhWolf** [comment]
LGTM 💯

**Review by HenrikhWolf — COMMENTED** [review]
LGTM 🤓👌

**Pull request merged**
