### PR TITLE
Implementación de firebase y autenticación

### PR DESCRIPTION
**Pull request by Matarratas777**
Co-Authored-By: EliasCode79 <61769763+EliasCode79@users.noreply.github.com>
Co-Authored-By: GADDIEL 

# Description
The database was implemented in the flights app to save emails and passwords in a Google database

- Imagen de WhatsApp 2023-01-24 a las 16 34 21

- 
Imagen de WhatsApp 2023-01-24 a las 16 34 50

Examples:

-This base was implemented so that there are no repeated accounts or that any user may suffer a hard time if someone tries to enter their account by mistake. since it will ask for your corresponding data

### CODE REVIEW

**Review by McFly1208 — APPROVED** [review]
LGTM

**Review by Leonardo-Aguirre-Ponce — APPROVED** [review]
LGTM

**Review by QuackDuster — APPROVED** [review]
LGTM

**Review by Zuack55 — APPROVED** [review]
Good Job

**Review by RobertoCarMed — APPROVED** [review]

**Pull request merged**
